name: Py Lambda Deploy
author: Mariam Maarouf
description: Deploy python code to AWS Lambda with dependencies in a separate layer.
inputs:
  requirements_txt:
    description: the name/path to the requirements.txt file
    required: true
    default: 'requirements.txt'
  lambda_layer_arn:
    description: The ARN for the Lambda layer the dependencies should be pushed to without the version (every push is a new version).
    required: true
  lambda_function_name:
    description: The Lambda function name. Check the AWS docs/readme for examples.
    required: true
  s3_bucket:
    description: S3 bucket where upload lambda zip code.
    required: true
  code_path:
    description: Path to the code.
    required: false
    default: './'
  architectures:
    description: Target architectures
    required: false
    default: 'x86_64'
  runtimes:
    description: Compatible runtimes in space-separated string
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.requirements_txt }}
    - ${{ inputs.lambda_layer_arn }}
    - ${{ inputs.lambda_function_name }}
    - ${{ inputs.code_path }}
    - ${{ inputs.s3_bucket }}
    - ${{ inputs.architectures }}
    - ${{ inputs.runtimes }}
branding:
  icon: 'layers'
  color: 'yellow'
